development:
  adapter: postgresql
  database: portfolio_data
  username:
  host: localhost

test:
  adapter: postgresql
  database: portfolio_data
  username:
  host: localhost

production:
  adapter: postgresql
  database: portfolio_data
  username:
